[package]
name = "soml-lang-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde = "1"
soml-lang = { path = ".." }

[[bin]]
name = "read"
path = "fuzz_targets/read.rs"
test = false
doc = false
bench = false

[[bin]]
name = "document"
path = "fuzz_targets/document.rs"
test = false
doc = false
bench = false

[[bin]]
name = "change"
path = "fuzz_targets/change.rs"
test = false
doc = false
bench = false

[[bin]]
name = "format"
path = "fuzz_targets/format.rs"
test = false
doc = false
bench = false
